### ISSUE TITLE
submission-api-data.yaml compile error

### ISSUE THREAD

**Issue by nikfonseca** [Interhyp/SubmissionAPI#23]
In openAPI descriptor **_submission-api-data.yaml_**:
- `OtherCapitalNeededLoanUsageKey` schema defines twice the same enum value **OTHER**, this causes generated enumerated class to not compile due to duplicated unique value
- `Estate` schema references external `schema api-schema-property-register.yaml#/components/schemas/PropertyRegister`, but the external file api-schema-property-register.yaml is not provided. As PropertyRegister schema is also present in _**submission-api-data.yaml**_, the file can be fixed via local reference:  ` $ref: '#/components/schemas/PropertyRegister'`

Due to above mentioned issues, model generation via swagger-codegen v3 ends in compilation error

**Comment by mohamed-asfour** [comment]
Hi @nikfonseca ,
Thank you reporting the 2 issues in our api. a new version (2.0.1) has been published with the fixes for the above 2 issues.
Best Regards!

**Comment by mohamed-asfour** [comment]
fixed in version 2.0.1
